# Tutorial 5: NumPy, Part I

## PHYS 2600, Spring 2019

## T5.1 - Importing and testing things out

One of the great features of Python is the huge number of available modules which implement commonly used algorithms and functions for us.  Most of these modules are widely used and thoroughly tested, but it's still always a good idea to make sure that you're getting what you think you are when you `import` something else!  ("Trust, but verify.")

The next cell tries to use the `sin` function from NumPy, but we forgot to import the module - if you run it now, it will just give an error message!  __Fix the cell by importing the `numpy` module__.  Make sure you use the standard shorthand alias of `np` (using `import ... as ...` syntax.)

Remember, anything we get from the module namespace must be referenced with the "dot notation", `<module>.<object>`.

In [1]:
### BEGIN SOLUTION
import numpy as np
### END SOLUTION



np.sin(np.pi/2)

1.0

Now let's test the `np.exp()` function, which is used to raise `e` to a power, i.e. `exp(x)` = $e^x$. 

In the cell below, use `print` statements to __verify the following simple identities__:
\\[
e^0 = 1 \\
e^1 = e \\
e^{-1} = 1/e
\\]

_(Remember, modules contain constants as well as functions!  Use `np.e` as the known value of e on the right-hand side.)_

In [2]:
print('%g = %g' % (np.exp(0), 1))
print('%g = %g' % (np.exp(1), np.e))
print('%g = %g' % (np.exp(-1), 1/np.e))

1 = 1
2.71828 = 2.71828
0.367879 = 0.367879


Building on our results so far, let's test one of the hyperbolic trig functions.  The definition of `sinh(x)` should be: 

$$
\sinh(x) = \frac{1}{2} \left( e^x - e^{-x} \right)
$$

In the cell below, __calculate `sinh(2)`__ in two ways, using `np.sinh()` and using `np.exp()`.  Verify that your results match!

In [3]:
LHS = np.sinh(2)
RHS = 1/2 * (np.exp(2) - np.exp(-2))

print('%g = %g' % (LHS, RHS))

3.62686 = 3.62686


## T5.2 - Making NumPy arrays

Let's get some practice with some of the more common ways of creating NumPy arrays.  This will be a mix of runnable examples, and short exercises.

Your job is to figure out how to use each of these functions!  There are a couple of good ways to see the usage instructions:

1. Use the `?` command, e.g. `?np.array` (on its own line.)  This is another __magic command__, i.e. it's a command for Jupyter itself; it will show some documentation for the given function.  You can also try the `??` magic command, which often has additional information (sometimes too much!)
2. Use your favorite search engine to find the official NumPy documentation for them!  (e.g. "numpy array" or "numpy linspace" usually does the trick.)

(For the `?` command, use the "x" at the top right of the pop-up window to close the function info, or the other button to open it in a new tab/window.)

### np.array

The first way to make an array is the `np.array()` function, which creates a new array by converting whatever input we give it.  __Run the cell below to see some examples__ (and feel free to modify them!)

In [ ]:
print(np.array([1,4,2,3]))
print(np.array([-3.3, -2.2, -1.1]))

### np.arange

Regularly-spaced ranges of numbers are very commonly used, especially for plotting functions as we'll see next time.  NumPy has a couple of ways to make such arrays natively!  First up, the `np.arange()` function.  The simplest way to use it is with a single argument, which does this:

In [ ]:
print(np.arange(10))

This function is actually much more flexible than that.  __Here are the basic rules for using `arange`:__

* With __one argument__, `np.arange(N)` gives every number from 0 up to N-1.
* With __two arguments__, `np.arange(M,N)` gives every number from M up to N-1.
* With __three arguments__, `np.arange(M,N,k)` gives every number from M up to N-1, _counting in steps of k._

Now __use `np.arange()` to produce the following arrays__, and print them out:

* An array of integers from 0 to 5, inclusive.  (i.e. `[0,1,...,5]`.)
* An array of integers from -3 to 3, inclusive.  (i.e. `[-3,-2,...,3]`.)
* An array of odd numbers from 5 to 11, inclusive.  (i.e. `[5,7,9,11]`.)
* An array of floats from 0 to 1, spaced by 1/10.  (i.e. `[0,0.1,0.2,...,0.9]`.)

In [4]:
print(np.arange(0,6))
print(np.arange(-3,4))
print(np.arange(5,12,2))
print(np.arange(0,1,0.1))


[0 1 2 3 4 5]
[-3 -2 -1  0  1  2  3]
[ 5  7  9 11]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


What do you expect to happen if you call `np.arange(M,N,k)` and `k` is negative?  Try using it with $k=-1$ in the box below and see what happens!  

Using what you learn from your experiments, __can you produce an array _counting backwards_ from 10 to 0?__

In [5]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### np.linspace

The `np.linspace()` function gives us another way to make regularly-spaced arrays, but instead of specifying the _step size_ like in `arange`, we specify the _number of points_ we want in total.  For example, to get the range `[0...9]` again:

In [ ]:
print(np.linspace(0,9,10))

Notice that unlike `range` and `arange`, __`linspace` includes both boundary values__ that you give in the resulting array!

__Use `np.linspace()` to produce the following arrays:__ (and print them.)

* An array of 20 points, equally spaced between -1 and 1.
* An array of floats from 0 to 1, spaced by 1/10.  (i.e. `[0,0.1,0.2,...,0.9]`)
* An array of 15 points, equally spaced from 0 to `2*pi`.  (You don't need `math`, since NumPy also contains math constants: pi is stored as `np.pi`.)

In [6]:
print(np.linspace(-1,1,20))
print(np.linspace(0,0.9,10))
print(np.linspace(0,2*np.pi, 15))

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.44879895 0.8975979  1.34639685 1.7951958  2.24399475
 2.6927937  3.14159265 3.5903916  4.03919055 4.48798951 4.93678846
 5.38558741 5.83438636 6.28318531]


### np.zeros (and friends)

If we know we want to create an array of a certain size, say by applying some formulas to an input array, it's often useful to __initialize__ the array we're creating to some value - most commonly, zero.  If we want an array of zeros, the `np.zeros()` function is a shortcut for making it:

In [ ]:
print(np.zeros(5))

There are a few cousins of this function worth knowing about: `np.ones` does the same thing but sets every value to 1 instead; `np.zeros_like` takes an existing array, and produces a new one with the __same shape__ but all values set to zero.  (You can probably guess what `np.ones_like` does!)

__Use these functions to create the following arrays:__

* Use `np.zeros_like` with `np.arange` to make a length-8 array of zeros.  (This is sort of contrived; usually, we would use `zeros_like` if we're working with an input array of unknown length that we want to match.)
* Use `np.ones` (and basic math operations) to make an array of length seven, with every entry equal to the number 7.

In [7]:

### BEGIN SOLUTION
print(np.zeros_like(np.arange(8)))
# In fact, linspace could have just made this list for us:
print(np.linspace(0,0,8))
print(np.ones(7) * 7)
### END SOLUTION


[0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0.]
[7. 7. 7. 7. 7. 7. 7.]


## T5.3 - Electromagnetic force

### Part A

The combination of electric and magnetic forces on a point charge is given by the Lorentz force law,

\\[
\mathbf{F} = q\mathbf{E} + q\mathbf{v} \times \mathbf{B}.
\\]

We can implement this force equation using NumPy arrays!  First, a quick introduction to vector math in NumPy.  Let's take the vectors we were using in class:

In [9]:
import numpy as np

v, w = np.array([2,1,3]), np.array([0,-3,1])
print(v, w)

[2 1 3] [ 0 -3  1]


Working it out by hand, the __cross product__ $v \times w$ is equal to the vector `[10, -2, -6]`.  You should be able to compute the __dot product__
\\[
v \cdot w = \sum_{i=1}^3 v_i w_i
\\]
yourself.  The NumPy functions corresponding to each of these are `np.cross(v,w)` and `np.dot(v,w)`, respectively.

First, use NumPy in the cell below to find the cross product $v \times w$ and the dot product $v \cdot w$, and __check that the answers are what you expect.__

In [10]:
print(np.dot(v,w))   # equal to 0.
print(np.cross(v,w)) # = [10, -2, -6] as given above.

0
[10 -2 -6]


The cross product satisfies two _identities:_

1. $\mathbf{w} \times \mathbf{v} = - \mathbf{v} \times \mathbf{w}$
2. $\mathbf{v} \times \mathbf{v} = 0$

Use NumPy to verify these identities, again using the vectors `v` and `w` we defined above.

In [11]:
print(np.cross(w,v)) # = [-10, 2, 6], minus v x w.
print(np.cross(v,v)) # = [0, 0, 0].


[-10   2   6]
[0 0 0]


### Part B

Now that you're familiar with the NumPy functions needed, __compute the EM force on a test charge__ in the following two cases:

- __Case A:__ A one-Coulomb charge is moving with velocity $\mathbf{v} = (2, -1, 0)$ is subject to a magnetic field $\mathbf{B} = (1,1,1)$.
- __Case B:__ A proton (charge $q = 1.6 \times 10^{-19}\ \rm{C}$) moving at $+6 \times 10^7$ m/s along the z-axis is subject to both an electric field $\mathbf{E} = (0,0,4)$ and a magnetic field $\mathbf{B} = (3, -3, 1)$.

__Save your answers for the force vectors to variables `F_A` (case A) and `F_B` (case B)__.

(The E and B fields are in appropriate SI units so that the force will come out in Newtons with no extra conversions or other numeric factors.)

In [12]:
v_A = np.array([2, -1, 0])
B_A = np.array([1,1,1])

F_A = np.cross(v_A, B_A)
print(F_A)

q_B = 1.6e-19
v_B = np.array([0, 0, 6e7])
E_B = np.array([0,0,4])
B_B = np.array([3,-3,1])

F_B = q_B * (E_B + np.cross(v_B, B_B))
print(F_B)

[-1 -2  3]
[2.88e-11 2.88e-11 6.40e-19]


In [13]:
## Tests to verify your force calculation above

print("F_A = ", F_A)
print("F_B = ", F_B)

import numpy.testing as npt

npt.assert_allclose(F_A, [-1,-2,3])
npt.assert_allclose(F_B, [2.9e-11, 2.9e-11, 6.4e-19], rtol=0.01)

F_A =  [-1 -2  3]
F_B =  [2.88e-11 2.88e-11 6.40e-19]


### Part C

For any force exerted on a moving particle, the instantaneous __power__ (work per unit time) is given by the dot product with velocity:

\\[
P = \mathbf{F} \cdot \mathbf{v}.
\\]

In the cell below, show that $P=0$ for case A (as expected, since no work is done by a magnetic field.)  Then find the power exerted by the EM force in case B.

In [14]:
P_A = np.dot(F_A, v_A)
print(P_A)

P_B = np.dot(F_B, v_B)
print(P_B)

0
3.84e-11
